version: "3"  

tasks:  
  default:
    cmds:  
      - task: generate 
  run:
    desc: "Run the post service"
    cmds:
      - |
        cd ./cmd/app
        go run main.go --config ../../config/config.yaml 
  generate:
    aliases:
      - gen  
    desc: "Generate code from proto files"  
    cmds:
      - protoc -I proto proto/user/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative