version: '3'

tasks:
  run_auth_service:
    desc: "Run the C# AuthService"
    cmds:
      - |
        cd ./AuthService
        dotnet run 
  
  run_post_service:
    desc: "Run the Go PostService"
    cmds:
      - |
        cd ./PostService
        task run
  
  run_comment_service:
    desc: "Run the Go CommentService"
    cmds:
      - |
        cd ./CommentService
        task run
        
  run_user_service:
    desc: "Run the C# UserService"
    cmds:
      - |
        cd ./UserService
        dotnet run

  run_api_getaway:
    desc: "Run the api getaway"
    cmds:
      - |
        cd ./ApiGetaway
        dotnet run
  
  run_chat_service:
    desc: "Run the C# ChatService"
    cmds:
      - |
        cd ./ChatService
        dotnet run
      
  run_all:
    desc: "Run both AuthService and PostService"
    deps:
      - run_auth_service
      - run_post_service
      - run_user_service
      - run_api_getaway
      - run_comment_service
      - run_chat_service